'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import type {Locale} from '@/lib/i18n';
export type {Locale} from '@/lib/i18n';
const en:Record<string,string>={
'nav.home':'Home','nav.hall':'Hall of Fame','nav.gacha':'Gacha','nav.profile':'Profile','nav.settings':'Settings','nav.post':'Post Issue','nav.notifications':'Notifications','nav.account':'Account','nav.signIn':'Sign in',
'auth.title':'Join Patch!','auth.email':'Email','auth.password':'Password','auth.signIn':'Sign in','auth.signUp':'Create account','auth.magic':'Send Magic Link','auth.or':'or','auth.close':'Close','auth.switchSignup':'Need an account? Create one','auth.switchSignin':'Already have an account? Sign in','auth.finishProfile':'Finish your profile','auth.language':'Language','auth.saving':'Saving…','auth.createdCheckEmail':'Account created. Check your email to confirm it.',
'home.live':'Live timeline','home.headline':'Your awkward message.','home.subheadline':'The internet patches it.','home.intro':'Post a real-life communication problem. People rewrite it into something sharper, funnier, more formal, or completely unhinged.',
'settings.title':'Settings','settings.profile':'Profile','settings.displayName':'Display Name','settings.username':'Username Handle','settings.bio':'Bio / Self-Introduction','settings.avatar':'Avatar URL','settings.language':'App Settings / Language','settings.save':'Save changes','settings.saved':'Saved','settings.saveError':'Could not save settings.','settings.signin':'Sign in to edit your profile, save patches, and contribute.','settings.description':'Shape your identity, language, and device settings.','settings.accountProfile':'Account & Profile','settings.publicIdentity':'Your public Patch! identity','settings.viewProfile':'View profile','settings.yourName':'Your name','settings.bioPlaceholder':'Tell people about you','settings.avatarLabel':'Profile Icon / Avatar URL','settings.appLanguage':'App Language','settings.appLanguageDescription':'Choose the language used by the Patch! interface.','settings.systemData':'System & Data','settings.systemDataDescription':'Reset local voting and temporary device state.','settings.clearCache':'Clear local cache','settings.accountActions':'Account Actions','settings.accountActionsDescription':'Sign out on this device or switch to another account.','settings.signOutSwitch':'Sign out / Switch account','settings.signingOut':'Signing out…','settings.appInfo':'App Information','settings.terms':'Terms of Service','settings.privacy':'Privacy Policy','settings.version':'Version',
'profile.history':'Patch history','profile.saved':'Saved Patches','profile.badges':'Badges','profile.issues':'Issues','profile.patches':'Patches','profile.merges':'Merges','profile.upvotes':'Upvotes','profile.empty':'No patches yet.','profile.yourProfile':'Your Profile','profile.signin':'Sign in to create and edit your Patch! identity.','profile.edit':'Edit Profile','profile.full':'Open full contribution profile','profile.preferences':'Edit account & preferences',
'feed.loading':'Loading the feed…','feed.noIssues':'No Issues yet.','feed.firstIssue':'Be the first person to post something the internet can patch.','feed.rewrites':'See rewrites'
};
const ja:Record<string,string>={...en,'nav.home':'ホーム','nav.hall':'殿堂入り','nav.gacha':'ガチャ','nav.profile':'プロフィール','nav.settings':'設定','nav.post':'Issueを投稿','nav.notifications':'通知','nav.account':'アカウント','nav.signIn':'ログイン','auth.title':'Patch!に参加','auth.email':'メールアドレス','auth.password':'パスワード','auth.signIn':'ログイン','auth.signUp':'アカウント作成','auth.magic':'マジックリンクを送る','auth.or':'または','auth.close':'閉じる','auth.switchSignup':'アカウントを作成する','auth.switchSignin':'すでにアカウントをお持ちですか？ログイン','auth.finishProfile':'プロフィールを完成させる','auth.language':'言語','auth.saving':'保存中…','auth.createdCheckEmail':'アカウントを作成しました。確認メールをチェックしてください。','home.live':'ライブタイムライン','home.headline':'あなたの気まずいメッセージ。','home.subheadline':'インターネットがパッチする。','home.intro':'現実のコミュニケーション問題を投稿。みんなが、もっと鋭く、面白く、丁寧に、あるいは完全にカオスな文章へ書き換えます.','settings.title':'設定','settings.profile':'プロフィール','settings.displayName':'表示名','settings.username':'ユーザーネーム','settings.bio':'自己紹介','settings.avatar':'アバターURL','settings.language':'アプリ設定 / 言語設定','settings.save':'変更を保存','settings.saved':'保存しました','settings.saveError':'設定を保存できませんでした。','settings.signin':'プロフィール編集、Patch保存、投稿にはログインしてください。','settings.description':'プロフィール、言語、端末設定を管理します。','settings.accountProfile':'アカウントとプロフィール','settings.publicIdentity':'公開されるPatch!プロフィール','settings.viewProfile':'プロフィールを見る','settings.yourName':'名前','settings.bioPlaceholder':'自己紹介を入力','settings.avatarLabel':'プロフィール画像 / アバターURL','settings.appLanguage':'アプリの言語','settings.appLanguageDescription':'Patch!のインターフェースで使用する言語を選択します。','settings.systemData':'システムとデータ','settings.systemDataDescription':'ローカル投票データと一時的な端末データをリセットします。','settings.clearCache':'ローカルキャッシュを削除','settings.accountActions':'アカウント操作','settings.accountActionsDescription':'この端末からログアウトするか、別のアカウントに切り替えます。','settings.signOutSwitch':'ログアウト / アカウント切替','settings.signingOut':'ログアウト中…','settings.appInfo':'アプリ情報','settings.terms':'利用規約','settings.privacy':'プライバシーポリシー','settings.version':'バージョン','profile.yourProfile':'プロフィール','profile.signin':'Patch!のプロフィールを作成・編集するにはログインしてください。','profile.edit':'プロフィールを編集','profile.full':'貢献プロフィールを開く','profile.preferences':'アカウントと設定を編集','feed.loading':'フィードを読み込んでいます…','feed.noIssues':'まだIssueがありません。','feed.firstIssue':'最初のIssueを投稿して、インターネットにパッチしてもらいましょう。','feed.rewrites':'書き換えを見る'};
const es:Record<string,string>={...en,'nav.home':'Inicio','nav.hall':'Salón de la Fama','nav.gacha':'Gacha','nav.profile':'Perfil','nav.settings':'Ajustes','nav.post':'Publicar Issue'};
const zh:Record<string,string>={...en,'nav.home':'首页','nav.hall':'名人堂','nav.gacha':'扭蛋','nav.profile':'个人资料','nav.settings':'设置','nav.post':'发布 Issue'};
const dict={en,ja,es,zh};
type Ctx={locale:Locale;setLocale:(x:Locale)=>void;t:(k:string)=>string};
const C=createContext<Ctx|null>(null);
export function I18nProvider({children}:{children:React.ReactNode}){const[locale,setLocaleState]=useState<Locale>('en');useEffect(()=>{const c=document.cookie.match(/(?:^|; )patch-locale=([^;]+)/)?.[1];const l=window.localStorage.getItem('patch-locale');const x=(l||c||navigator.language).toLowerCase().split('-')[0];setLocaleState(x==='ja'||x==='es'||x==='zh'?x:'en')},[]);const setLocale=(x:Locale)=>{setLocaleState(x);document.cookie=`patch-locale=${x}; Path=/; Max-Age=31536000; SameSite=Lax`;window.localStorage.setItem('patch-locale',x)};const t=(k:string)=>dict[locale][k]??dict.en[k]??k;return <C.Provider value={useMemo(()=>({locale,setLocale,t}),[locale])}>{children}</C.Provider>}
export function useI18n(){const v=useContext(C);if(!v)throw new Error('useI18n must be used inside I18nProvider');return v}
