'use client';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { Issue, PatchItem, PatchStyle, ContentLanguage } from '@/lib/types';
import { createPatch as persistPatch, fetchIssues, hasDatabaseConfig, mergePatch as persistMerge, upvotePatch as persistUpvote } from '@/lib/patchDb';
import { getActorId } from '@/lib/identity';
import { initialIssues } from '@/lib/mockData';
type NewIssue={title:string;body:string;category?:string;language?:ContentLanguage};type NewPatch={issueId:string;text:string;style:PatchStyle;parentPatchId?:string|null};type IssueContextValue={issues:Issue[];isLoading:boolean;dbEnabled:boolean;error:string|null;addIssue:(input:NewIssue)=>Promise<string>;addPatch:(input:NewPatch)=>Promise<void>;upvotePatch:(issueId:string,patchId:string)=>Promise<void>;mergePatch:(issueId:string,patchId:string)=>Promise<void>;getIssue:(id:string)=>Issue|undefined};const IssueContext=createContext<IssueContextValue|null>(null);const VOTED_PATCHES_KEY='patch-voted-patches';
function readVotedPatches(){if(typeof window==='undefined')return new Set<string>();try{const value=JSON.parse(localStorage.getItem(VOTED_PATCHES_KEY)??'[]');return new Set(Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[]);}catch{return new Set<string>();}}function writeVotedPatches(value:Set<string>){if(typeof window!=='undefined')localStorage.setItem(VOTED_PATCHES_KEY,JSON.stringify([...value]));}function sortPatches(patches:PatchItem[]){return [...patches].sort((a,b)=>b.votes-a.votes||Date.parse(b.createdAt)-Date.parse(a.createdAt));}
export function IssueProvider({children}:{children:React.ReactNode}){const dbEnabled=hasDatabaseConfig();const[issues,setIssues]=useState<Issue[]>(initialIssues);const[isLoading,setIsLoading]=useState(dbEnabled);const[error,setError]=useState<string|null>(null);useEffect(()=>{let mounted=true;if(!dbEnabled){setIsLoading(false);return()=>{mounted=false;};}fetchIssues().then(data=>{if(!mounted)return;setIssues(data);setError(null);}).catch(reason=>{if(!mounted)return;console.error(reason);setError('Supabase could not be loaded. Showing the local MVP data instead.');setIssues(initialIssues);}).finally(()=>{if(mounted)setIsLoading(false);});return()=>{mounted=false;};},[dbEnabled]);
const addIssue=async(input:NewIssue)=>{setError(null);const response=await fetch('/api/issues',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,actorId:getActorId()})});const payload=(await response.json()) as{issue?:Issue;error?:string};if(!response.ok||!payload.issue)throw new Error(payload.error||'Could not create the Issue.');setIssues(current=>[payload.issue!,...current]);return payload.issue.id;};const addPatch=async(input:NewPatch)=>{setError(null);const patch=await persistPatch(input);setIssues(current=>current.map(issue=>issue.id===input.issueId?{...issue,patches:sortPatches([patch,...issue.patches])}:issue));};const upvotePatch=async(issueId:string,patchId:string)=>{const voted=readVotedPatches();if(voted.has(patchId))return;setError(null);if(!dbEnabled){setIssues(current=>current.map(issue=>issue.id!==issueId?issue:{...issue,patches:sortPatches(issue.patches.map(p=>p.id===patchId?{...p,votes:p.votes+1}:p))}));voted.add(patchId);writeVotedPatches(voted);return;}const updated=await persistUpvote(patchId);setIssues(current=>current.map(issue=>issue.id!==issueId?issue:{...issue,patches:sortPatches(issue.patches.map(p=>p.id===patchId?updated:p))}));voted.add(patchId);writeVotedPatches(voted);};const mergePatch=async(issueId:string,patchId:string)=>{setError(null);const merged=await persistMerge(issueId,patchId);setIssues(current=>current.map(issue=>issue.id!==issueId?issue:{...issue,mergedPatchId:merged.mergedPatchId,mergedAt:merged.mergedAt,patches:issue.patches.map(p=>({...p,isMerged:p.id===patchId}))}));};const value=useMemo<IssueContextValue>(()=>({issues,isLoading,dbEnabled,error,addIssue,addPatch,upvotePatch,mergePatch,getIssue:id=>issues.find(issue=>issue.id===id)}),[issues,isLoading,dbEnabled,error]);return <IssueContext.Provider value={value}>{children}</IssueContext.Provider>;}
export function useIssues(){const context=useContext(IssueContext);if(!context)throw new Error('useIssues must be used inside IssueProvider');return context;}
