'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Check,LogIn,LogOut,Save,Settings as SettingsIcon,UserCircle,Trash2,ExternalLink} from 'lucide-react';
import {useAuth} from '@/context/AuthContext';
import {getSupabaseClient} from '@/lib/supabase/client';
import {useI18n} from '@/components/I18nProvider';
import {LanguageSelector} from '@/components/LanguageSelector';
import {completeProfile} from '@/lib/auth/actions';

export default function SettingsPage(){
 const{user,profile,openAuth,saveProfile}=useAuth();const{t,locale}=useI18n();
 const[username,setUsername]=useState('');const[displayName,setDisplayName]=useState('');const[bio,setBio]=useState('');const[avatarUrl,setAvatarUrl]=useState('');const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[error,setError]=useState('');const[signingOut,setSigningOut]=useState(false);
 useEffect(()=>{if(profile){setUsername(profile.username);setDisplayName(profile.displayName);setBio(profile.bio);setAvatarUrl(profile.avatarUrl)}else if(user){const s=getSupabaseClient();if(s)void s.from('profiles').select('username,display_name,bio,avatar_url').eq('actor_id',user.id).maybeSingle().then(({data})=>{if(data){setUsername(data.username??'');setDisplayName(data.display_name??'');setBio(data.bio??'');setAvatarUrl(data.avatar_url??'')}})}},[profile,user]);
 async function save(e:React.FormEvent){e.preventDefault();if(!user)return;setSaving(true);setSaved(false);setError('');try{const lang=locale.toUpperCase() as 'EN'|'JA'|'ES'|'ZH';await completeProfile({username,displayName,bio,avatarUrl,language:lang});await saveProfile({username:username.trim().replace(/^@/,''),displayName:displayName.trim(),bio:bio.trim(),avatarUrl:avatarUrl.trim(),language:locale});setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Could not save settings.')}finally{setSaving(false)}}
 async function signOut(){const s=getSupabaseClient();if(!s)return;setSigningOut(true);try{await s.auth.signOut();window.location.href='/'}finally{setSigningOut(false)}}
 function clearLocalData(){try{localStorage.removeItem('patch-voted-patches');sessionStorage.clear();window.location.reload()}catch{window.location.reload()}}
 return <main className="min-h-screen"><div className="mx-auto max-w-3xl px-4 pb-24 pt-6 md:px-8 md:pt-12"><div className="mb-10"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3 py-1.5 text-xs font-bold text-zinc-400"><SettingsIcon size={13}/>{t('settings.title')}</div><h1 className="text-4xl font-black tracking-tight md:text-6xl">{t('settings.title')}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-500">Manage your profile, app language, local data, and account.</p></div>
 {!user?<section className="rounded-3xl border border-white/10 bg-white/[0.025] p-7"><h2 className="text-xl font-black">{t('auth.title')}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{t('settings.signin')}</p><button onClick={openAuth} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-zinc-950"><LogIn size={16}/>{t('auth.signIn')}</button></section>:<div className="space-y-5">
  <form onSubmit={save} className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-black">Account & Profile</h2><p className="mt-1 text-xs text-zinc-600">Your public Patch! identity</p></div><Link href={`/profile/${user.id}`} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-zinc-400 hover:text-white">View profile</Link></div><div className="mt-6 flex items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-full bg-white/10 text-xl font-black">{avatarUrl?<img src={avatarUrl} alt="" className="h-full w-full object-cover"/>:<UserCircle size={30} className="text-zinc-600"/>}</div><div><p className="text-sm font-bold">{displayName||'Your name'}</p><p className="text-xs text-zinc-600">{username?'@'+username:'@username'}</p></div></div><div className="mt-6 grid gap-4"><Field label="Display Name *" value={displayName} setValue={setDisplayName} placeholder="Your name"/><Field label="Username Handle" value={username} setValue={setUsername} placeholder="patchsmith" prefix="@"/><label className="text-xs font-bold text-zinc-500">Bio / Self Introduction<textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={300} rows={4} placeholder="Tell people about you" className="mt-2 w-full resize-none rounded-2xl border border-white/10 bg-zinc-950 px-4 py-3 text-sm text-white outline-none"/></label><Field label="Profile Icon / Avatar URL" value={avatarUrl} setValue={setAvatarUrl} placeholder="https://…"/></div><div className="mt-5 border-t border-white/5 pt-5"><p className="text-xs font-bold text-zinc-600">Email</p><p className="mt-1 break-all text-sm text-zinc-300">{user.email||'—'}</p></div>{error&&<div className="mt-5 rounded-2xl border border-red-400/20 bg-red-400/[0.06] p-4 text-sm text-red-200">{error}</div>}<button disabled={saving} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-5 py-4 text-sm font-black text-zinc-950 disabled:opacity-50"><Save size={17}/>{saving?'Saving…':saved?'Saved':t('settings.save')}{saved&&<Check size={16}/>}</button></form>
  <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><h2 className="text-lg font-black">App Settings / 言語設定</h2><p className="mt-1 text-xs text-zinc-600">Choose the language used by the app UI.</p><div className="mt-5"><LanguageSelector/></div></section>
  <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><h2 className="text-lg font-black">System & Data</h2><p className="mt-1 text-xs text-zinc-600">Reset local voting/cache state on this device.</p><button type="button" onClick={clearLocalData} className="mt-5 inline-flex items-center gap-2 rounded-2xl border border-white/10 px-4 py-3 text-sm font-bold text-zinc-300 hover:bg-white/[0.04]"><Trash2 size={16}/>Clear local cache</button></section>
  <section className="rounded-3xl border border-red-400/15 bg-red-400/[0.025] p-6"><h2 className="text-lg font-black">Account Actions</h2><p className="mt-1 text-xs text-zinc-600">Sign out on this device or switch to another account.</p><button type="button" disabled={signingOut} onClick={signOut} className="mt-5 inline-flex items-center gap-2 rounded-2xl border border-red-300/20 px-4 py-3 text-sm font-bold text-red-200 disabled:opacity-50"><LogOut size={16}/>{signingOut?'Signing out…':'Sign out / Switch account'}</button></section>
  <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><h2 className="text-lg font-black">App Information</h2><div className="mt-4 flex items-center justify-between text-sm"><span className="text-zinc-500">Version</span><span className="font-bold text-zinc-300">v1.0.0</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><a href="/terms" className="flex items-center justify-between rounded-2xl border border-white/10 px-4 py-3 text-sm font-bold text-zinc-300 hover:bg-white/[0.04]">Terms of Service<ExternalLink size={15}/></a><a href="/privacy" className="flex items-center justify-between rounded-2xl border border-white/10 px-4 py-3 text-sm font-bold text-zinc-300 hover:bg-white/[0.04]">Privacy Policy<ExternalLink size={15}/></a></div></section>
 </div>}
 </div></main>
}
function Field({label,value,setValue,placeholder,prefix}:{label:string;value:string;setValue:(v:string)=>void;placeholder:string;prefix?:string}){return <label className="text-xs font-bold text-zinc-500">{label}<div className="mt-2 flex rounded-2xl border border-white/10 bg-zinc-950 px-4"><span className="py-3 text-zinc-600">{prefix}</span><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent px-2 py-3 text-sm text-white outline-none"/></div></label>}
